version: 1.0.{build}
os: Visual Studio 2015
build_script:
- cmd: mkdir build && cd build && cmake .. -DEASTL_BUILD_BENCHMARK:BOOL=ON -DEASTL_BUILD_TESTS:BOOL=ON && cmake --build . --config Debug && cmake --build . --config Release
test_script:
- cmd: cd test && ctest -C Release -V && cd .. && cd benchmark && ctest -C Release -V
